### ISSUE TITLE
Suggestion: Change color

### ISSUE THREAD

**Issue by rezaeisr18** [xerez4/github-crash-course#1]
It looks better if the main title is a bit more orange.

The styling rule could be changed like this bro:

```css
h1 {
  color: #efa82e;
}
```
